#!/usr/bin/bash
usage() { echo "\
########################################################################
# FILE: inst
#
# PURPOSE: Check for older scripts in ~/bin directory that need replacing
#
# USAGE: inst [-i][-v]
#
# PARAMETERS:
#   -i     Install newer files from here to ~/bin
#   -v     Verbose mode
#
# EXAMPLE: inst -v
#
# MODIFICATION HISTORY:
#   2020/09/27, SK Hushing III. Original issue for Fedora.
########################################################################" >&2
exit; }

#----[ Initializations ]----#
script=`basename $0`

#----[ Handle command line options ]----#
inst=
v=
while getopts 'a:b:cv' opt; do
    case $opt in
    i) inst=1;;
    v) v=$((v + 1));;
    \?) usage;;
    esac
done
shift "$((OPTIND - 1))"
if [ "$1" = "help" ]; then usage; fi

#----[ Body of script ]----#
dash="============================================================"
for lcl in *; do
    rmt=~/bin/$lcl
    [ ! -x $lcl ] && continue
    [ "$lcl" = "$script" ] && continue
    # [ ! -f $rmt ] && continue
    [ $v ] && echo "$dash $lcl"
    diff $rmt $lcl >/dev/null 2>&1
    s=$?
    # if [ $s -eq 1 ]; then
    if [ $s -ne 0 ]; then
	echo $s $lcl
	if [ $inst ]; then
	    echo "cp $lcl $rmt"
	fi
    fi
done
