#!/usr/bin/perl
########################################################################
# FILE: path
#
# PURPOSE: list directories in PATH, one on each line
#
# USAGE: path
#
# MODIFICATION HISTORY:
#   2020/09/16 SK Hushing III. Original issue for Fedora.
########################################################################
    my @dirs = split(/:/,$ENV{PATH});
    foreach my $dir (@dirs) {
	print "$dir\n";
    }
