#!/usr/bin/perl
########################################################################
# FILE: redo
#
# PURPOSE: Recreate my Fedora user environment from scratch
#
# USAGE: redo
#
# MODIFICATION HISTORY:
#   2020/09/17 SK Hushing III. Original issue for Fedora.
########################################################################

#----[ Misc initializations ]----#
my $script = `basename $0`; chomp($script);

#----[ Start in home directory ]----#
my $HOME = $ENV{HOME};
print "$script: starting in $HOME\n";
chdir "$HOME";

#----[ Create aliases ]----#
my $rc = ".bashrc";
my $rco = "$rc.orig";
if (! -e $rco) {
    print "$script: backing up $rc to $rco\n";
    system("cp -p $rc $rco");
    print "$script: adding aliases to $rc\n";
    open(RC, ">>", "$rc") or die "Can't open $rc";
    print RC qq(alias la='ls -lFa --color=auto'\n);
    print RC qq(alias lx='ls -CF --color=auto'\n);
    print RC qq(alias lt='ls -lFtr --color=auto'\n);
    close(RC);
}

#----[ Create utility scripts ]----#
my $bin = "$HOME/bin";
if (! -d "$bin") {
    print "$script: creating $bin\n";
    system("mkdir $bin");
}

#----[ Create scripts ]----#
chdir "$bin";
path("newpath") if ! -f "newpath";
psg("newpsg") if ! -f "newpsg";

#----[ Subroutine to create the path script ]----#
sub path {
    my ($path_fn) = @_;
    print "Creating $path_fn\n";
    open (PATH, ">$path_fn");
    print PATH <<'EOF';
#!/usr/bin/perl
########################################################################
# FILE: path
#
# PURPOSE: list directories in PATH, one on each line
#
# USAGE: path
#
# MODIFICATION HISTORY:
#   2020/09/16 SK Hushing III. Original issue for Fedora.
########################################################################
my @dirs = split(/:/,$ENV{PATH});
foreach my $dir (@dirs) {
    print "$dir\n";
}
EOF
    close(PATH);
    system("chmod +x $path_fn");
}

#----[ Subroutine to create the psg script ]----#
sub psg {
    my ($psg_fn) = @_;
    print "Creating $psg_fn\n";
    open (PSG, ">$psg_fn");
    print PSG <<'EOF';
#!/usr/bin/perl
########################################################################
# FILE: psg
#
# PURPOSE: filter running processes from ps command
#
# USAGE: psg
#
# MODIFICATION HISTORY:
#   2020/09/16 SK Hushing III. Original issue for Fedora.
########################################################################

#----[ Parse output from PS command ]----#
# UID          PID    PPID  C STIME TTY          TIME CMD
# root           1       0  0 13:42 ?        00:00:08 /usr/lib/systemd/systemd --switched-root --system --deserialize 17

open(PS, "ps -ef|");
while (<PS>) {
    ($uid,$pid,$ppid,$c,$stime,$tty,$time,$cmd) = split;
    print "$pid $cmd\n";
}
close(PS);
EOF
    close(PSG);
    system("chmod +x $psg_fn");
}
