#!/usr/bin/perl
sub usage() { print STDERR
"########################################################################
# FILE: backup
#
# PURPOSE: Backup my favorite directories to a tar file under ~/Backups
#
# USAGE: backup [-v] [dirs]
#
# PARAMETERS: 
#   -v           Verbose mode
#   [dirs]       List of directories to backup. Default is built-in.
#
# EXAMPLE: backup -v Backups/dot_files bin Develop Pictures
#
# MODIFICATION HISTORY:
#   2020/09/27, SK Hushing III. Original issue for Fedora.
########################################################################
"; exit }

use strict;
use warnings;
use Getopt::Long;
Getopt::Long::Configure("bundling");

#----[ Initializations ]----#
my $script = `basename $0`; chomp($script);
my $date = `date +%Y_%m%d_%H%M`; chomp($date);
my $home = $ENV{HOME};
my $dotdir = "Backups/dot_files";
my $tarfile = "$home/Backups/backup_$date.tar";
chdir($home);

#----[ Handle command line options ]----#
my $dirs = "$dotdir bin Develop Pictures Reports";
my $v = 0;
GetOptions (
    "v+"  => \$v,
) or die "$script: Aborted.
";
usage() if scalar(@ARGV) > 0 && $ARGV[0] eq "help";

#----[ Process list of directories to backup ]----#
if (scalar(@ARGV) > 0) {
    $dirs = "";
    foreach my $dir (@ARGV) {
	die("$script: No such directory ($dir)\n") if ! -d $dir;
	$dirs .= " " if $dirs ne "";
	$dirs .= $dir;
    }
    print STDERR "$script: backing up specified directories\n";
} else {
    print STDERR "$script: backing up default directories\n";
}

#----[ Print some variables for understanding ]----#
if ($v) {
    print "date:    $date\n";
    print "home:    $home\n";
    print "dirs:    $dirs\n";
    print "tarfile: $tarfile\n";
}

#----[ Grab current copies of dot files to dot_files directory ]----#
print "Copying some hidden/dot files to dir: $dotdir\n" if $v;
system("cp -p .bash_logout $dotdir/.");
system("cp -p .bash_profile $dotdir/.");
system("cp -p .bashrc $dotdir/.");
system("cp -p .exrc $dotdir/.");
system("cp -p .gitconfig $dotdir/.");
system("cp -p .gvimrc $dotdir/.");
system("cp -p .viminfo $dotdir/.");

#----[ Create tar command ]----#
my $vopt = $v>1 ? "v" : "";
my $cmd = "tar c${vopt}f $tarfile $dirs";

#----[ Backup to tarfile ]----#
print "Backing up specified files\n" if $v;
print "$cmd\n" if $v;
system($cmd);
