#!/usr/bin/perl
sub usage() { print STDERR
'########################################################################
# FILE: dft
#
# PURPOSE: List size/free of interesting mounted filesystems
#
# USAGE: dft [-h] [string]
#
# PARAMETERS: 
#   string     Optional - only list FS that match string
#   -h         Suppress printing the header line.
#   -v         Verbose mode
#
# EXAMPLE: dft -v 
#
# MODIFICATION HISTORY:
#   2020/09/21, SK Hushing III. Original issue for Fedora.
########################################################################
'; exit }

use strict;
use warnings;
use Getopt::Long;
Getopt::Long::Configure("bundling");

#----[ Initializations ]----#
my $script = `basename $0`; chomp($script);

#----[ Handle command line options ]----#
my $h = 0;
my $v = 0;
GetOptions (
    "h"   => \$h,
    "v+"  => \$v,
) or die ("$script: * Unsupported option\n");
usage() if scalar(@ARGV) > 0 && $ARGV[0] eq "help";

#----[ Handle command line arguments ]----#
my $string = scalar(@ARGV) > 0 ? $ARGV[0] : "";
my $narg = @ARGV;
if (scalar(@ARGV) > 1) {
    print STDERR "$script: * Unexpected argument(s) ignored\n";
}

#----[ Body of script ]----#
my $cmd = "df -h";
print "#----- Beginning dft ($cmd)\n" if $v;
open(DF, "-|", "$cmd 2>/dev/null") or die "error opening df pipe\n";
while (my $line = <DF>) {
    chomp($line);
    print "$line\n" if $line =~ "Filesystem" && !$h;
    # next if $line =~ "tmpfs";
    # next if $line =~ "boot";
    next if $line !~ "^\/dev\/";
    next if $string ne "" && $line !~ "$string";
    print "$line\n";
    # my ($fs,$sz,$us,$av,$pct,$mnt) = split(/  */, $line);
    # print "$fs $sz $pct $mnt\n";
}
close(DF);
print "#----- Finished dft\n" if $v;

