#!/bin/bash
########################################################################
# FILE: li
#
# PURPOSE: Long directory list, no group, show inode numbers
#
# USAGE: li [directory]
#
# MODIFICATION HISTORY:
#   2020/09/23, SK Hushing III. Original issue for Fedora.
########################################################################
ls -lFoi --color=auto $@
