#!/usr/bin/perl
sub usage() { print STDERR
'########################################################################
# FILE: lines
#
# PURPOSE: Print descending line numbers to show window height
#
# USAGE: lines [nlines]
#
# OPTIONS:
#   nlines   The number of line numbers to print. Default LINES or 60.
#
# MODIFICATION HISTORY:
#   2020/09/18, SK Hushing III. Original issue for Fedora.
#   2026/09/04, SKH. Use LINES for default.
########################################################################
'; exit }
use strict;
use warnings;

#----[ Handle command line arguments ]----#
my $nlines = $ARGV[0] // $ENV{'LINES'} // 60;

#----[ Print descending line numbers ]----#
for (my $i = $nlines; $i > 0; $i--) {
    print "$i";
    print "\n" if $i > 1;
    print " " if $i == 1;
}
