#!/bin/bash
########################################################################
# FILE: ll
#
# PURPOSE: Long directory list, no group column, show filetypes
#
# USAGE: ll [directory]
#
# MODIFICATION HISTORY:
#   2020/10/07, SK Hushing III. Original issue for Fedora.
########################################################################
ls -lFo --color=auto $@
