#!/usr/bin/perl
sub usage() { print STDERR
'########################################################################
# FILE: ruler
#
# PURPOSE: Print a 2-line horizontal character ruler
#
# USAGE: ruler [width]
#
# ARGUMENTS:
#   width   Width of ruler in characters. Default is COLUMNS or 80.
#
# MODIFICATION HISTORY:
#   2020/09/19, SK Hushing III. Original issue for Fedora.
#   2026/09/02, SKH. Updated on a-shell.
########################################################################
'; exit }

use strict;
use warnings;
use File::Basename;

# Print usage if first argument is help
usage() if scalar(@ARGV) > 0 && $ARGV[0] eq "help";

#----[ Initializations ]----#
my $script = basename($0);
my $width = $ARGV[0] // $ENV{'COLUMNS'} // 80;

#----[ Print column numbers tens and ones ]----#
for (my $i=1; $i<=$width/10; $i++) { printf "%10i", $i }; print "\n";
for (my $i=1; $i<=$width; $i++) { print $i % 10 }; print "\n";
